# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine

WORKDIR /app

# Copy the entire repository into the Docker image
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set environment variables (can be overridden at runtime)
ENV CANVAS_API_KEY="1072~ELaLNEQQCB9EPJMBtEzTR6GT7fENvM9Jff8BxtXX6PAkhYav7KP4HUhmK7CrZa3n"
ENV GOOGLE_API_KEY=""
ENV GRADESCOPE_EMAIL=""
ENV GRADESCOPE_PASSWORD=""

# Run the MCP server using canvas.py as the entry point
CMD ["python", "canvas.py"]
